"""Pydantic models for DeepSeek structured output and the resolved document metadata.

LLM output models are lenient about presentation (whitespace, duplicates, overly long
lists are normalized) but strict about types, so malformed responses fail validation
and are retried.
"""

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, BeforeValidator, ConfigDict, Field, field_validator

from src.rag.departments import DEPARTMENTS

DOCUMENT_TYPES = (
    "policy",
    "procedure",
    "guide",
    "handbook",
    "manual",
    "faq",
    "checklist",
    "reference",
    "form",
    "template",
    "announcement",
    "training",
    "report",
    "other",
)
MAX_LIST_ITEMS = 20
MAX_ITEM_CHARS = 120


def _clean_list(value: Any) -> Any:
    """Strip, drop empties, de-duplicate case-insensitively and cap list length."""
    if value is None:
        return []
    if not isinstance(value, list):
        return value  # let pydantic reject non-lists
    seen: set[str] = set()
    items: list[str] = []
    for item in value:
        if not isinstance(item, str):
            return value  # type error surfaces during validation
        text = " ".join(item.split())[:MAX_ITEM_CHARS]
        if text and text.casefold() not in seen:
            seen.add(text.casefold())
            items.append(text)
    return items[:MAX_LIST_ITEMS]


def _clean_text(limit: int):
    def clean(value: Any) -> Any:
        if isinstance(value, str):
            text = " ".join(value.split())[:limit]
            return text or None
        return value

    return clean


StrList = Annotated[list[str], BeforeValidator(_clean_list)]
ShortText = Annotated[str | None, BeforeValidator(_clean_text(300))]
LongText = Annotated[str | None, BeforeValidator(_clean_text(1200))]


class GroundedValue(BaseModel):
    """A factual field the model must support with a verbatim quote from the source."""

    model_config = ConfigDict(extra="ignore")

    value: Annotated[str, BeforeValidator(_clean_text(200))]
    evidence: Annotated[str, BeforeValidator(_clean_text(400))]


class LLMDocumentMetadata(BaseModel):
    """Document-level metadata generated by DeepSeek (validated, then grounded)."""

    model_config = ConfigDict(extra="ignore")

    title: ShortText = None
    document_type: str = "other"
    suggested_primary_department: str | None = None
    secondary_departments: StrList = Field(default_factory=list)
    relevant_roles: StrList = Field(default_factory=list)
    topics: StrList = Field(default_factory=list)
    keywords: StrList = Field(default_factory=list)
    summary: LongText = None
    intended_audience: ShortText = None
    purpose: ShortText = None
    major_sections: StrList = Field(default_factory=list)
    referenced_systems: StrList = Field(default_factory=list)
    referenced_products: StrList = Field(default_factory=list)
    referenced_policies: StrList = Field(default_factory=list)
    document_identifiers: StrList = Field(default_factory=list)
    owner: GroundedValue | None = None
    version: GroundedValue | None = None
    effective_date: GroundedValue | None = None
    review_date: GroundedValue | None = None

    @field_validator("owner", "version", "effective_date", "review_date", mode="before")
    @classmethod
    def _empty_fact(cls, value: Any) -> Any:
        if isinstance(value, dict) and not str(value.get("value") or "").strip():
            return None
        if isinstance(value, str) and not value.strip():
            return None
        return value

    @field_validator("document_type", mode="before")
    @classmethod
    def _document_type(cls, value: Any) -> Any:
        if value is None:
            return "other"
        if isinstance(value, str):
            normalized = value.strip().casefold().replace(" ", "_")
            return normalized if normalized in DOCUMENT_TYPES else "other"
        return value

    @field_validator("suggested_primary_department", mode="before")
    @classmethod
    def _department(cls, value: Any) -> Any:
        if isinstance(value, str):
            return _match_department(value)
        return value

    @field_validator("secondary_departments", mode="after")
    @classmethod
    def _departments(cls, value: list[str]) -> list[str]:
        matched = [_match_department(v) for v in value]
        return list(dict.fromkeys(d for d in matched if d))


def _match_department(value: str) -> str | None:
    lookup = {d.casefold(): d for d in DEPARTMENTS}
    return lookup.get(" ".join(value.split()).casefold())


class LLMSection(BaseModel):
    """One semantic section: a contiguous block range plus descriptive fields."""

    model_config = ConfigDict(extra="ignore")

    start_block: int
    end_block: int
    title: ShortText = None
    summary: LongText = None
    keywords: StrList = Field(default_factory=list)
    roles: StrList = Field(default_factory=list)
    context: Annotated[str | None, BeforeValidator(_clean_text(500))] = None


class LLMSegmentation(BaseModel):
    model_config = ConfigDict(extra="ignore")

    sections: list[LLMSection]


class MetadataConflict(BaseModel):
    field: str
    kept_value: str
    kept_from: Literal["source", "hr_selection"]
    other_value: str
    other_from: Literal["llm", "source"]


class SourceMetadata(BaseModel):
    """Facts read from the file itself (front matter, document properties)."""

    raw: dict[str, Any] = Field(default_factory=dict)
    title: str | None = None
    owner: str | None = None
    version: str | None = None
    effective_date: str | None = None
    review_date: str | None = None
    department: str | None = None
    document_identifiers: list[str] = Field(default_factory=list)
    keywords: list[str] = Field(default_factory=list)


FactSource = Literal["source", "llm_grounded"]


class DocumentMetadata(BaseModel):
    """Resolved document metadata with explicit provenance for every field group."""

    title: str
    title_source: Literal["metadata", "heading", "llm", "filename"]
    department: str  # HR-selected, authoritative
    source: SourceMetadata
    llm: LLMDocumentMetadata | None = None
    llm_status: Literal["succeeded", "fallback", "skipped"] = "skipped"
    llm_error: str | None = None
    # Factual fields resolved from source metadata first, then grounded LLM output.
    owner: str | None = None
    owner_source: FactSource | None = None
    version: str | None = None
    version_source: FactSource | None = None
    effective_date: str | None = None
    effective_date_source: FactSource | None = None
    review_date: str | None = None
    review_date_source: FactSource | None = None
    conflicts: list[MetadataConflict] = Field(default_factory=list)
    ungrounded_fields: list[str] = Field(default_factory=list)
    source_outline: list[str] = Field(default_factory=list)
