"""Flatten chunk metadata into ChromaDB-compatible scalars (and back).

Convention (applied uniformly):

- ``str``/``int``/``float``/``bool`` values are stored as-is;
- lists and dicts are stored as a JSON string under ``<name>_json``;
- ``None`` values are omitted (ChromaDB metadata cannot hold nulls).

Key prefixes make provenance explicit: ``src_*`` values were read from the file itself,
``llm_*`` values were generated by DeepSeek; unprefixed keys are system/structural
values (IDs, HR-selected department, heading path, pages, offsets, timestamps).
"""

from __future__ import annotations

import json
import math
from typing import Any

JSON_SUFFIX = "_json"


def flatten_metadata(values: dict[str, Any]) -> dict[str, str | int | float | bool]:
    flat: dict[str, str | int | float | bool] = {}
    for key, value in values.items():
        if value is None:
            continue
        if isinstance(value, bool | int | str):
            flat[key] = value
        elif isinstance(value, float):
            if not math.isfinite(value):
                raise ValueError(f"Metadata '{key}' is not a finite number")
            flat[key] = value
        elif isinstance(value, list | tuple | dict):
            flat[f"{key}{JSON_SUFFIX}"] = json.dumps(
                list(value) if isinstance(value, tuple) else value,
                ensure_ascii=False,
                sort_keys=True,
                default=str,
            )
        else:
            raise TypeError(f"Unsupported metadata type for '{key}': {type(value).__name__}")
    return flat


def unflatten_metadata(flat: dict[str, Any]) -> dict[str, Any]:
    """Inverse of :func:`flatten_metadata` (``*_json`` keys decoded, suffix removed)."""
    values: dict[str, Any] = {}
    for key, value in flat.items():
        if key.endswith(JSON_SUFFIX) and isinstance(value, str):
            values[key[: -len(JSON_SUFFIX)]] = json.loads(value)
        else:
            values[key] = value
    return values
